INSERT INTO USER (USER_NAME, PASSWORD, ROLES, NAME, STATUS, FAILED_ATTEMPTS, LOCKED_DATE) VALUES ('jpg', '$2a$10$GOxr7SqSyuwsYf6UySF4Oukl5iDGtfnxudGfCPf3D5GK8g0v.n7om', 'USER', 'JPG', 'LOCKED', 3, {ts '2021-08-05 10:40:52.69'});
INSERT INTO USER (USER_NAME, PASSWORD, ROLES, NAME, STATUS, FAILED_ATTEMPTS) VALUES ('admin', '$2a$10$u/5vONLk6Hi7IWFPVHEIluGJtF9fEJLGMUEF/8LIUtRGs6UOjWgJW', 'ADMIN', 'ADMIN user', 'ACTIVE', 0);

-- jpg: 123
-- admin: 890*